### ISSUE TITLE
Función Avanzar (funcion movimiento)

### ISSUE THREAD

**Issue by micaelhg** [IC-ULS/edd-taller2-g2#13]
esta función hará avanzar al jugador entre los calabozos en la dirección que anteriormente retorna [opcion valida]

**Comment by Kakarotinho** [comment]
Void Avanzar(Nodo*nodo,int opcion)
{
       If (opcion==1)
       {
              nodo=nodo->derecho;
       }
       If (opcion==2)
       {
              nodo=nodo->abajo;
       }
       If (opcion==3)
       {
              nodo=nodo->izquierdo;
       }
       If (opcion==4)
       {
              nodo=nodo->arriba;
       }
}

**Comment by Kakarotinho** [comment]
si la opción es 
1= avanzar a la derecha(hijo derecho)
2= avanzar abajo(hijo abajo)
3= avanzar izquierda(hijo izquierdo)
4=avanzar arriba(hijo arriba)
